name: AI Review Reusable

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:

      # 1) Reusable Workflow リポジトリを checkout
      #    ここに "scripts/run_ai_review.py" がある想定。
      - name: Check out this (Reusable Workflow) repo
        uses: actions/checkout@v3
        with:
          # 自分自身のリポジトリ (= スクリプトがあるレポ)
          repository: shonakamura000/ai-code-review  # ← あなたの公開リポジトリ名に変える
          ref: main   # 必要に応じてブランチやタグ

      # 2) Caller (ユーザ) リポジトリを checkout
      #    "caller" というサブフォルダに配置しておく
      - name: Check out caller repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: caller

      - name: Debug directory structure
        run: |
          echo "Listing directory structure..."
          ls -R
          echo "Done listing directory structure."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Debug Secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ← 必要ならこのまま
        run: |
          echo "Debugging secrets from reusable workflow..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY was not passed."
            exit 1
          else
            echo "OPENAI_API_KEY is set."
          fi

          # GITHUB_TOKEN が無くても構わないならチェック削除してOK
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Error: GITHUB_TOKEN was not passed."
            exit 1
          else
            echo "GITHUB_TOKEN is set."
          fi

      - name: Install dependencies
        run: |
          pip install openai requests

      - name: Verify Python Packages
        run: |
          pip list

      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running AI Review script..."
          # Reusable Workflow リポジトリの scripts/ ディレクトリに入っているスクリプトを実行
          # Caller のコードは "caller" フォルダ配下にある
          python scripts/run_ai_review.py --target=caller
