name: AI Review Reusable

on:
  workflow_call:
    # 「secrets」で宣言すると、値が隠蔽された状態で渡せる
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 受け取った secrets をデバッグ出力 (必要に応じて省略可)
      - name: Debug Secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Debugging secrets from reusable workflow..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY was not passed."
            exit 1
          else
            echo "OPENAI_API_KEY is set."
          fi

          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Error: GITHUB_TOKEN was not passed."
            exit 1
          else
            echo "GITHUB_TOKEN is set."
          fi

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install openai requests

      - name: Verify Python Packages
        run: |
          echo "Verifying installed packages..."
          pip list

      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running AI Review script..."
          # ここでAIレビュー用のPythonスクリプトを実行
          python scripts/run_ai_review.py
