name: AI Review Reusable

on:
  workflow_call:
    inputs:
      openai_api_key:
        required: true
        type: string
      github_token:
        required: true
        type: string

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      # コードをチェックアウト
      - name: Check out code
        uses: actions/checkout@v3

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Inputsのデバッグ
      - name: Debug Inputs and Environment Variables
        env:
          OPENAI_API_KEY: ${{ inputs.openai_api_key }}
          GITHUB_TOKEN: ${{ inputs.github_token }}
        run: |
          echo "Debugging Inputs and Environment Variables..."
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "Error: openai_api_key is not provided as an input."
            exit 1
          else
            echo "openai_api_key is set."
          fi

          if [ -z "${GITHUB_TOKEN}" ]; then
            echo "Error: github_token is not provided as an input."
            exit 1
          else
            echo "github_token is set."
          fi

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install openai requests

      # 依存関係インストールの確認
      - name: Verify Python Packages
        run: |
          echo "Verifying installed packages..."
          pip list

      # AIレビューを実行
      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ inputs.openai_api_key }}
          GITHUB_TOKEN: ${{ inputs.github_token }}
        run: |
          echo "Running AI Review script..."
          python scripts/run_ai_review.py
