name: AI Review Reusable

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        required: true

permissions:
  contents: write       
  pull-requests: write  

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      # 1) Reusable Workflow リポジトリ (このレポ) を checkout
      - name: Check out AI Review Script (Public repo)
        uses: actions/checkout@v3
        with:
          repository: shonakamura000/ai-code-review  
          ref: feat-review-classification
          path: ai_review_repo

      # 2) Caller (ユーザ) リポジトリを checkout
      - name: Check out caller repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: caller
          fetch-depth: 0

      - name: Debug directory structure
        run: |
          echo "Listing directory structure..."
          ls -R
          echo "Done listing directory structure."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Debug Secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          echo "Debugging secrets from reusable workflow..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY was not passed."
            exit 1
          fi
          echo "OPENAI_API_KEY is set."

          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Error: GITHUB_TOKEN is not passed."
            exit 1
          fi
          echo "GITHUB_TOKEN is set."

      - name: Install dependencies
        run: |
          pip install openai requests

      - name: Verify Python Packages
        run: |
          pip list

      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running AI Review script..."
          cd caller
          python ../ai_review_repo/src/scripts/run_ai_review.py
